"""Task modeline description ve due_date eklendi

Revision ID: 358bd5dffbe8
Revises: c3e84393235e
Create Date: 2025-10-30 02:52:09.778833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358bd5dffbe8'
down_revision: Union[str, Sequence[str], None] = 'c3e84393235e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
